//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeatonFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        [Required(ErrorMessage = "A unique ID is required")]
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Customer's first Name required")]
        public string CustFirstName { get; set; }
        [Required(ErrorMessage = "Customer's last name required")]
        public string CustLastName { get; set; }
        [Required(ErrorMessage = "Customer's state required")]
        public string CustState { get; set; }
        [Required(ErrorMessage = "Customer's Sales Year to Date required")]
        public int CustSalesYTD { get; set; }
        [Required(ErrorMessage = "Customer's Previous Years Sales required")]
        public int CustSalesPrevious { get; set; }
    }
}
